// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-GK9VKglKxzshKPB72TCB8zGE7XoC5o',
    appId: '1:958440252796:android:92760300a31a793f67b0f9',
    messagingSenderId: '958440252796',
    projectId: 'we-chat-a0f14',
    storageBucket: 'we-chat-a0f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-5wcC6JqZbVTzevBNaKQhtLvH23MSWw',
    appId: '1:958440252796:ios:3d8b779e865dc27467b0f9',
    messagingSenderId: '958440252796',
    projectId: 'we-chat-a0f14',
    storageBucket: 'we-chat-a0f14.appspot.com',
    androidClientId: '958440252796-1sq9430d7g954jgsn9hkt3dv34q5p8qu.apps.googleusercontent.com',
    iosClientId: '958440252796-r0u6c0cbqee5rtlnrgea19upf0fm3ned.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppp',
  );
}
